---
- hosts: all
  gather_facts: false
  roles:
    - role: keyscan

- hosts: all
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: server
  become: true
  roles:
    - role: k3s/server

- hosts: agent
  become: true
  roles:
    - role: k3s/agent
