- name: Install open iSCSI
  package:
    name: open-iscsi
    state: present
  when: groups[server_group].index(inventory_hostname) == 0

- name: Install GPG
  package:
    name: gpg
    state: present
  when: groups[server_group].index(inventory_hostname) == 0

- name: Download Helm armoured GPG key
  ansible.builtin.get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /etc/apt/helm.asc
    mode: '0644'
    force: true
  when: groups[server_group].index(inventory_hostname) == 0

- name: Unarmour Helm GPG key
  shell: gpg --dearmor < /etc/apt/helm.asc > /etc/apt/trusted.gpg.d/helm.gpg
  when: groups[server_group].index(inventory_hostname) == 0

- name: Add Helm repo
  apt_repository:
    filename: example-repo
    repo: 'deb https://baltocdn.com/helm/stable/debian/ all main'
  when: groups[server_group].index(inventory_hostname) == 0

- name: Install Helm
  package:
    name: helm
    state: present
  when: groups[server_group].index(inventory_hostname) == 0

- name: Add longhorn chart repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"
  when: groups[server_group].index(inventory_hostname) == 0

- name: Deploy latest version of Longhorn Volume Manager
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
  when: groups[server_group].index(inventory_hostname) == 0
